[FCXPINFRA-76] Added Tiger token to requests
mercadolibre/fury-little_monster-gem pull request #88
Opened 2024-02-20 16:57 UTC by w00x

2024-02-21 13:33 UTC, arcticfalcon requested changes

2024-02-21 13:33 UTC, arcticfalcon commented on lib/little_monster/tiger/auth.rb
> +        token = new_shark_token
faltaría algun cacheo

2024-02-21 14:00 UTC, w00x commented on lib/little_monster/tiger/auth.rb
> +        token = new_shark_token
ok, buscare alguna gema

2024-02-21 14:08 UTC, arcticfalcon commented on lib/little_monster/tiger/auth.rb
> +        token = new_shark_token
fijate que en fury-api ya lo hace

2024-02-21 14:18 UTC, w00x commented on lib/little_monster/tiger/auth.rb
> +        token = new_shark_token
es que ese es el cache de rails

2024-02-21 15:28 UTC, lufunes commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
colocar URL real

2024-02-21 15:31 UTC, lufunes commented on lib/little_monster/tiger/auth.rb
> +      def new_shark_token
Hay instalaciones de LM API fuera de shark, quizas se puede agregar una config para no buscar el client credential de kubernetes y no ir a tiger (retornar directamente nil)

A futuro estas instalaciones deberian hacer login mediante el client credential de tiger

2024-02-21 15:33 UTC, lufunes commented on spec/mock/responses/tiger_token.json
> +  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkNGYyMWRkLTgwZTItNGY2ZC1iOGY0LWE4OTE2ZDY0YTFhZiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsX2luZm8iOnsiZW1haWwiOiJleGFtcGxlIiwiZnVsbF9uYW1lIjoiZXhhbXBsZSIsInVzZXJuYW
es necesario un token similar al real acá? teniendo en cuenta que es un repo público

2024-02-21 15:36 UTC, w00x commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
en la configuración cuando la utilicen deberían agregar la url real

2024-02-21 15:38 UTC, lufunes commented on lib/little_monster/tiger/auth.rb
> +        token = new_shark_token
una cosa a tener en cuenta es que no debería desaparecer el valor de la cache hasta no obtener el valor nuevo, aunque esté vencido. En rails nos pasó que se descartaba el valor almacenado en la cache (que aún era válido por varios minutos más) y luego no poder generar un nuevo token (o descargar un certificado) por un error temporal de red o la API

2024-02-21 15:42 UTC, w00x commented on spec/mock/responses/tiger_token.json
> +  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkNGYyMWRkLTgwZTItNGY2ZC1iOGY0LWE4OTE2ZDY0YTFhZiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsX2luZm8iOnsiZW1haWwiOiJleGFtcGxlIiwiZnVsbF9uYW1lIjoiZXhhbXBsZSIsInVzZXJuYW
creo que no es necesario, lo cambio

2024-02-23 15:33 UTC, lufunes commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
el valor por defecto no debería ser la url real? para evitar problemas en los entornos donde no se configuró áun el valor

2024-02-23 15:34 UTC, lufunes commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
sobretodo porque por defecto tenemos la funcionalidad habilitada (enable_tiger_token:true)

2024-02-23 15:37 UTC, lufunes approved these changes
Dejo solo el comentario sobre la config por defecto. Teniendo en cuenta todos los LMs instalados, conviene dejar habilitado por defecto este feature y que explícitamente se apague? si está habilitado por defecto, deberíamos dejar la URL por defecto?

2024-02-23 15:46 UTC, w00x commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
ya que el api_url tampoco esta el original definido quise seguir esa linea, pero la puedo agregar

2024-02-23 15:48 UTC, w00x commented
> Dejo solo el comentario sobre la config por defecto. Teniendo en cuenta todos los LMs instalados, conviene dejar habilitado por defecto este feature y que explícitamente se apague? si está habilitado por defecto, deberíamos dejar la URL por defecto?

Agregare la url por defecto

2024-02-23 16:04 UTC, w00x commented on lib/little_monster.rb
> +      tiger_api_url: 'http://tiger',
creo que mejor la agregan al momento de usarla, ya que puede ser para Meli, FaaP, Sulamerica, etc... en implementación tal vez la obtengan de una ENV

2024-03-01 13:18 UTC, closed without merging